# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-09 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_drink_place_of_origin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drink',
            new_name='DrinkInfo',
        ),
    ]
