# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-09 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_auto_20180709_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkinfo',
            name='description',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
