# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-09 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0006_auto_20180709_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkinfo',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
