# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-09 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0007_drinkinfo_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkinfo',
            name='timestamp',
        ),
    ]
