# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0009_drinkinfo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkinfo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drinkinfo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
